import ETC_LOGO from "../assets/etc-logo.png";

export const APP_CONSTANTS = {
	APP_SCHOOL_NAME: "Eastern Tayabas College",
	APP_DESCRIPTION: "Attendance Management System for Eastern Tayabas College",
	APP_TITLE: "Attendance Management System | App",
	APP_LOGO: ETC_LOGO,
	APP_SUBMARK_LOGO: ETC_LOGO,
	APP_LOGO_HORIZONTAL: ETC_LOGO,
	PLEASE_WAIT: "Please wait...",
	WELCOME_TO: "Welcome to ",
	ALL_RIGHTS_RESERVE: "All rights reserved.",
	FORGOT_PASSWORD: "Forgot Password",
	CONTINUE: "Continue",
	DONT_HAVE_AN_ACCOUNT: "Don't have an account?",
	ALREADY_HAVE_AN_ACCOUNT: "Already have an account?",
	SIGN_IN: "Sign in",
	SIGN_UP: "Sign up",
	EMAIL: "Email",
	PHONE_NUMBER: "Phone Number",
	PASSWORD: "Password",
	CURRENT_PASSWORD: "Current Password",
	NEW_PASSWORD: "New Password",
	ENTER_PASSWORD: "Enter password",
	ENTER_EMAIL: "Enter email",
	ENTER_PHONE_NUMBER: "Enter phone number",
	OR_LOGIN_WITH: "OR LOG IN WITH",
	CONTINUE_WITH_GOOGLE: "Continue with Google",
	CONTINUE_WITH_FACEBOOK: "Continue with Facebook",
	MEMBER_LOGIN: "Member Login",
	LOGIN_PAGE_TAGLINE: "Eastern Tayabas College Attendance Management System",
	SAMPLE_EMAIL: "example@gmail.com",
	PASSWORD_REQUIREMENT: "Enter at least 8+ characters",
	FULLNAME: "Full Name",
	SAMPLE_FULLNAME: "John Doe",
	CREATE_AN_ACCOUNT: "Create an account",
	USER_TYPE: "User type",
	SELECT_USER_TYPE: "Select user type",
	OR_SIGN_UP_WITH: "or sign up with",
	BY_SIGNING_UP: "By signing up, you agree with",
	TERMS_OF_USE: "Terms of Use",
	PRIVACY_POLICY: "Privacy Policy",
	PRIVATE_TO_YOU: "Private To You",
	FIRST_NAME: "First Name",
	MIDDLE_NAME: "Middle Name",
	LAST_NAME: "Last Name",
	ACCOUNT: "Account",
	PREFERENCE: "Preference",
	RECEIVE_MONTHLY_PRODUCT_UPDATES: "Receive monthly product updates",
	SEE_INFO_ABOUT_PEOPLE_VIEW_PROFILE: "See info about people who view my profile",
	SAVE_INFORMATION: "Save Information",
	USERNAME: "Username",
	ENTER_USERNAME: "Enter username",
	ENTER_FIRST_NAME: "Enter First Name",
	ENTER_MIDDLE_NAME: "Enter Middle Name",
	ENTER_LAST_NAME: "Enter Last Name",
	SAMPLE_FIRST_NAME: "John",
	SAMPLE_MIDDLE_NAME: "Anonymous",
	SAMPLE_LAST_NAME: "Doe",
	SAMPLE_USERNAME: "johnDoe",
	SIGN_UP_WITH_GOOGLE: "Sign up with Google",
	SIGN_UP_WITH_FACEBOOK: "Sign up with Facebook",
	ADD_LISTING: "Add Listing",
	SEARCH_ELLIPSIS: "Search...",
	CHECK_AVAILABILITY: "Check Availability",
	NO_AMENITIES_AVAILABLE: "No amenities available",
	REVIEWS: "Reviews",
	NO_LISTING_FOUND: "No Listing Found",
	LISTING_TYPE: "Listing Type",
	STATUS: "Status",
	TAGS: "Tags",
	PRICE: "Price",
	RESULTS: "Results",
	MAX_FILES: 5,
	MAX_FILE_SIZE: 500 * 1024,
	INFORMATION: "Information",
	SAVE_SEARCH: "Save Search",
	CURRENCY_SYMBOL: "₱",
	NO_IMAGES_AVAILABLE: "No images available",
	LOT_SIZE: "Lot size",
	FLOOR_SIZE: "Floor size",
	ADDRESS: "Address",
	LOCATION: "Location",
	AREAS_NEARBY: "Areas Nearby",
	ADDRESS_NOT_AVAILABLE: "Address not available",
	TILE_LAYER_URL: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
	TILE_LAYER_ATTRIBUTION:
		'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap</a> contributors',
	UNTITLED_LISTING: "Untitled Listing",
	NOT_GRID_VERIFIED: "Not GRID Verified",
	NO_NEARBY_AREAS_LISTED: "No Nearby Area listed",
	DEFAULT_LOCATION: { lat: 14.6384007, lng: 121.0550602 },
	DEFAULT_LAT: 14.6384007,
	DEFAULT_LNG: 121.0550602,
	DEFAULT_LIMIT: 10,
	RECENT_ACTIVITY: "Recent Activity",
	PINNED: "Pinned",
	NO_PINNED_ITEM: "No Pinned Item",
	OVERVIEW: "Overview",
	WELCOME: "Welcome!",
	OWNER: "Owner",
	UNKNOWN: "Unknown",
	UPLOADED_BY: "Uploaded by",
	CURRENCY: "Php",
	UPGRADE: "Upgrade",
};
