export const ERROR = {
	"401": {
		title: "401",
		message: "Please log in to access this page.",
		subTitle: "Unauthorized Access",
		buttonText: "Go to Login",
		buttonLink: "/login",
		bgColor: "bg-info",
		hoverColor: "hover:bg-info-bold",
		buttonAction: undefined,
	},
	"403": {
		title: "403",
		message: "You don't have permission to view this page.",
		subTitle: "Access Denied",
		buttonText: "Go Home",
		buttonLink: "/",
		bgColor: "bg-danger",
		hoverColor: "hover:bg-danger-bold",
		buttonAction: undefined,
	},
	"404": {
		title: "404",
		message: "The page or item you're looking for might have been moved or deleted.",
		subTitle: "Page not found",
		buttonText: "Go Home",
		buttonLink: "/",
		bgColor: "bg-info",
		hoverColor: "hover:bg-info-bold",
		buttonAction: undefined,
	},
	itemNotAvailable: {
		title: "404",
		message: "The listing you're looking for might have been deleted or does not exist.",
		subTitle: "Listing not found",
		buttonText: "Go Home",
		buttonLink: "/",
		bgColor: "bg-info",
		hoverColor: "hover:bg-info-bold",
		buttonAction: undefined,
	},
	maintenance: {
		title: "🚧",
		message: "Our site is currently undergoing maintenance. Please check back later.",
		subTitle: "We'll be back soon",
		buttonText: "Refresh",
		buttonLink: "",
		bgColor: "bg-warning",
		hoverColor: "hover:bg-warning-bold",
		buttonAction: () => window.location.reload(),
	},
	offline: {
		title: "🌐",
		message: "You are currently offline.",
		subTitle: "Please check your internet connection and try again.",
		buttonText: "Retry",
		bgColor: "bg-info",
		hoverColor: "hover:bg-info-bold",
		buttonAction: () => window.location.reload(),
	},
} as const;
